// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX7603GKW6STLrsjFF8gbVf4v3NEpk-a0',
    appId: '1:914285097439:web:your_web_app_id',
    messagingSenderId: '914285097439',
    projectId: 'wsm3-app',
    authDomain: 'wsm3-app.firebaseapp.com',
    storageBucket: 'wsm3-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX7603GKW6STLrsjFF8gbVf4v3NEpk-a0',
    appId: '1:914285097439:android:909c892022a091e5ccd46a',
    messagingSenderId: '914285097439',
    projectId: 'wsm3-app',
    storageBucket: 'wsm3-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX7603GKW6STLrsjFF8gbVf4v3NEpk-a0',
    appId: '1:914285097439:ios:your_ios_app_id',
    messagingSenderId: '914285097439',
    projectId: 'wsm3-app',
    storageBucket: 'wsm3-app.firebasestorage.app',
    iosBundleId: 'com.example.wsm3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX7603GKW6STLrsjFF8gbVf4v3NEpk-a0',
    appId: '1:914285097439:macos:your_macos_app_id',
    messagingSenderId: '914285097439',
    projectId: 'wsm3-app',
    storageBucket: 'wsm3-app.firebasestorage.app',
    iosBundleId: 'com.example.wsm3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX7603GKW6STLrsjFF8gbVf4v3NEpk-a0',
    appId: '1:914285097439:windows:your_windows_app_id',
    messagingSenderId: '914285097439',
    projectId: 'wsm3-app',
    authDomain: 'wsm3-app.firebaseapp.com',
    storageBucket: 'wsm3-app.firebasestorage.app',
  );
}